Repository CheeUp/CheeUp-BE, pull requests merged in 2025-01, with the labels that each got.

#35 SCRUM-297-DB-docker : 포스트그레 DB 도커 추가
  db/master/initdb.d/init.sql
  db/master/initdb.d/insert_jobs.sql
  db/master/initdb.d/insert_skills.sql
  docker-compose.yml
  readme.md
Labels: ✨ Feature

#47 ✨feat: 게시판 CRUD API
  build.gradle
  src/main/java/com/cheeup/apiPayload/code/error/codes/CommunityErrorCode.java
  src/main/java/com/cheeup/apiPayload/code/success/codes/CommunitySuccessCode.java
  src/main/java/com/cheeup/apiPayload/exception/GlobalExceptionHandler.java
  src/main/java/com/cheeup/apiPayload/exception/handler/BadRequestException.java
  src/main/java/com/cheeup/apiPayload/exception/handler/NotFoundException.java
  src/main/java/com/cheeup/converter/community/BoardMapper.java
  src/main/java/com/cheeup/domain/community/Board.java
  src/main/java/com/cheeup/repository/BoardRepository.java
  src/main/java/com/cheeup/service/community/BoardService.java
  src/main/java/com/cheeup/service/community/BoardServiceImpl.java
  src/main/java/com/cheeup/web/controller/BoardController.java
  src/main/java/com/cheeup/web/dto/community/BoardDto.java
  src/main/resources/application.yml
Labels: ✨ feat

#53 49 fix 취업 공고 등록 수정
  src/main/java/com/cheeup/apiPayload/code/error/codes/ValidationErrorCode.java
  src/main/java/com/cheeup/apiPayload/exception/GlobalExceptionHandler.java
  src/main/java/com/cheeup/converter/jobnotice/JobMapper.java
  src/main/java/com/cheeup/repository/common/JobRepository.java
  src/main/java/com/cheeup/service/jobnotice/JobNoticeServiceImpl.java
  src/main/java/com/cheeup/validation/annotation/ExistFileType.java
  src/main/java/com/cheeup/validation/annotation/ExistJobDescriptionType.java
  src/main/java/com/cheeup/validation/validator/ExistFileTypeValidator.java
  src/main/java/com/cheeup/validation/validator/ExistJobDescriptionTypeValidator.java
  src/main/java/com/cheeup/web/dto/jobnotice/JobNoticeDto.java
  src/main/java/com/cheeup/web/dto/jobnotice/PostJobNoticeDto.java
Labels: 🐛 fix

#55 ✨ feat: 포트폴리오 생성 기능
  src/main/java/com/cheeup/apiPayload/ApiResponse.java
  src/main/java/com/cheeup/apiPayload/code/success/codes/PortfolioSuccessCode.java
  src/main/java/com/cheeup/apiPayload/exception/GlobalExceptionHandler.java
  src/main/java/com/cheeup/apiPayload/exception/handler/ResourceNotFoundException.java
  src/main/java/com/cheeup/converter/portfolio/PortfolioMapper.java
  src/main/java/com/cheeup/domain/portfolio/Portfolio.java
  src/main/java/com/cheeup/repository/member/MemberRepository.java
  src/main/java/com/cheeup/repository/portfolio/PortfolioRepository.java
  src/main/java/com/cheeup/service/portfolio/PortfolioService.java
  src/main/java/com/cheeup/service/portfolio/PortfolioServiceImpl.java
  src/main/java/com/cheeup/web/controller/PortfolioController.java
  src/main/java/com/cheeup/web/dto/portfolio/CreatePortfolioDto.java
Labels: ✨ feat

#52 :hammer: refactor: 포트폴리오 성과 주관기관 추가
  src/main/java/com/cheeup/domain/portfolio/PortfolioAward.java
  src/main/java/com/cheeup/domain/portfolio/PortfolioCertificate.java
  src/main/java/com/cheeup/domain/portfolio/PortfolioLanguage.java
Labels: 🔨 refactor

#54 41 회원 추가 및 삭제 api
  db/master/initdb.d/init.sql
  src/main/java/com/cheeup/apiPayload/code/success/codes/MemberSuccessCode.java
  src/main/java/com/cheeup/converter/member/MemberMapper.java
  src/main/java/com/cheeup/domain/member/Member.java
  src/main/java/com/cheeup/service/member/MemberService.java
  src/main/java/com/cheeup/service/member/MemberServiceImpl.java
  src/main/java/com/cheeup/web/controller/member/MemberController.java
  src/main/java/com/cheeup/web/dto/member/CreateMemberDto.java
Labels: ✨ feat

#74 :sparkles: 티어, 경험치 추가
  src/main/java/com/cheeup/web/dto/member/ReadMemberDto.java
Labels: ✨ feat

#76 Feature/내 게시글 조회 기능 추가
  src/main/java/com/cheeup/apiPayload/code/success/codes/MyPageSuccessCode.java
  src/main/java/com/cheeup/converter/community/MyPostMapper.java
  src/main/java/com/cheeup/converter/member/MemberMapper.java
  src/main/java/com/cheeup/domain/community/Post.java
  src/main/java/com/cheeup/repository/comunity/MyPageRepository.java
  src/main/java/com/cheeup/service/community/MyPageService.java
  src/main/java/com/cheeup/service/community/MyPageServiceImpl.java
  src/main/java/com/cheeup/web/controller/post/MyPageController.java
  src/main/java/com/cheeup/web/dto/common/Pagination.java
  src/main/java/com/cheeup/web/dto/community/MyPostDto.java
  src/main/java/com/cheeup/web/dto/community/ReadMyPostsDto.java
Labels: ✨ feat

#75 Feature/게시글 생성 기능
  db/master/initdb.d/init.sql
  src/main/java/com/cheeup/apiPayload/code/success/codes/CommunitySuccessCode.java
  src/main/java/com/cheeup/apiPayload/exception/GlobalExceptionHandler.java
  src/main/java/com/cheeup/converter/community/PostMapper.java
  src/main/java/com/cheeup/domain/community/Board.java
  src/main/java/com/cheeup/domain/community/Post.java
  src/main/java/com/cheeup/repository/community/BoardRepository.java
  src/main/java/com/cheeup/repository/community/PostRepository.java
  src/main/java/com/cheeup/service/community/BoardServiceImpl.java
  src/main/java/com/cheeup/service/community/PostService.java
  src/main/java/com/cheeup/service/community/PostServiceImpl.java
  src/main/java/com/cheeup/web/controller/PostController.java
  src/main/java/com/cheeup/web/dto/community/CreatePostDto.java
Labels: ✨ feat

#79 Feature/회원이 스크랩한 게시글 조회 API
  src/main/java/com/cheeup/apiPayload/code/success/codes/MyPageSuccessCode.java
  src/main/java/com/cheeup/converter/member/MemberMapper.java
  src/main/java/com/cheeup/repository/comunity/ScrappedPostRepository.java
  src/main/java/com/cheeup/service/community/MyPageService.java
  src/main/java/com/cheeup/service/community/MyPageServiceImpl.java
  src/main/java/com/cheeup/web/controller/post/MyPageController.java
Labels: ✨ feat
